#!/usr/bin/python

import random, string

def getVal(a):
    total = 0
    for i in a :
        total += ord(i)
    return total

def getString():
    passw = ''
    while getVal(passw) < 3440:
        passw += ''.join(random.choice(string.ascii_lowercase))
    if getVal(passw) > 3525:
        return getString()
    passw += chr(3566 - getVal(passw))
    return passw

print getString();
